# Generated by Django 6.0.2 on 2026-03-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_user_cartitem_variations'),
        ('stores', '0004_variaton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variaton',
            new_name='Variation',
        ),
    ]
